---
# Users are able to get only one gkit per life
one-gkit-per-life: true

# Users are able to get a gkit if they log out event if they did not die (only works if one-gkit-per-life: true)
reset-on-logout: true

# Use built in permission system even if using PurePerms
force-builtin-permissions: false

# Sign text (capitals don't matter)
sign-text: "[Gkits]"
...
